warmup_epochs: 20
warmup_lr: 0.00015
lr: 0.002
min_lr: 0.000002
t_max: 250
epochs: 250

model:
  NAME: BaseCls
  encoder_args:
    NAME: DENetEncoder
    block: 'DEBlock'
    blocks: [2, 2, 2, 1]
    strides: [1, 4, 4, 1]
    width: 96
    in_channels: 4
    sa_layers: 1
    sa_use_res: True
    radius: 0.15
    radius_scaling: 1.5
    nsample: 32
    expansion: 1 #4
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: False
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'gelu'
    norm_args:
      norm: 'bn'
  cls_args: 
    NAME: ClsHead
    num_classes: 15
    mlps: [512, 256]
    norm_args: 
      norm: 'bn1d'
