warmup_epochs: 10
warmup_lr: 0.001
lr: 0.01
min_lr: 0.00001
t_max: 100
epochs: 100

datatransforms:
  train: [ChromaticAutoContrast, PointsToTensor, PointCloudScaling, PointCloudXYZAlign, PointCloudRotation, PointCloudJitter, ChromaticDropGPU, ChromaticNormalize]
  val: [PointsToTensor, PointCloudXYZAlign, ChromaticNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [1.0, 1.0]
    angle: [0, 0, 1]
    jitter_sigma: 0.0
    jitter_clip: 0.0

model:
  NAME: BaseSeg
  encoder_args:
    NAME: DENetEncoder
    bn_after: True
    blocks: [2,4,4,4,4]
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1 
    sa_use_res: True 
    width: 32
    in_channels: 4
    expansion: 1 #4
    radius: 0.1
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: False
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'gelu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: DENetDecoder
    decoder_stages: 4
    decoder_layers: 1
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: null
    norm_args:
      norm: 'bn'

batch_size: 8
